



AddErrCode(  800 , "3번째 인자값을 잘못 주었습니다.(0: nitgen,1: bioapi)");
AddErrCode(  801 , "리더기를 오픈하지 못했습니다");
AddErrCode(  802 , "단말기에 토큰가 없습니다");
AddErrCode(  803 , "토큰에 문제가 있습니다");
AddErrCode(  804 , "토큰에 문제가 있습니다");
AddErrCode(  805 , "잠긴 토큰입니다");
AddErrCode(  805 , "인식할 수 없는 토큰입니다");
AddErrCode(  807 , "리더기를 오픈하지 못했습니다");
AddErrCode(  808 , "단말기에 토큰가 없습니다");
AddErrCode(  809 , "토큰에 문제가 있습니다");
AddErrCode(  810 , "토큰에 문제가 있습니다");
AddErrCode(  811 , "잠긴 토큰입니다");
AddErrCode(  812 , "인식할 수 없는 토큰입니다");
AddErrCode(  813 , "SspMod_SelectFile에서 실패했습니다");
AddErrCode(  814 , "SspMod_SelectFile에서 실패했습니다");
AddErrCode(  815 , "토큰 읽기에 실패했습니다");
AddErrCode(  816 , "토큰 리더기를 오픈하지 못했습니다");
AddErrCode(  817 , "단말기에 토큰가 없습니다");
AddErrCode(  818 , "토큰에 문제가 있습니다");
AddErrCode(  819 , "SspMod_EstablishSessKey에서 에러가 발생했습니다");
AddErrCode(  820 , "잠긴 토큰 입니다");
AddErrCode(  821 , "인식할 수 없는 토큰입니다");
AddErrCode(  822 , "SspMod_SelectFile에서 에러가 발생했습니다");
AddErrCode(  823 , "SspMod_SelectFile에서 에러가 발생했습니다");
AddErrCode(  824 , "SspMod_SelectFile에서 에러가 발생했습니다");
AddErrCode(  825 , "DSS_FP_Initialize를 호출하지 않았습니다. ");
AddErrCode(  826 , "이미 DSS_FP_Initialize를 호출했습니다.");
AddErrCode(  827 , "bioapi20.dll 모듈을 읽어오지 못했습니다.");
AddErrCode(  828 , "BioAPI_Init 의 Address를 읽어오지 못했습니다.");
AddErrCode(  829 , "BioAPI_Terminate 의 Address를 읽어오지 못했습니다.");
AddErrCode(  830 , "BioAPI_EnumBSPs 의 Address를 읽어오지 못했습니다.");
AddErrCode(  831 , "BioAPI_BSPLoad 의 Address를 읽어오지 못했습니다.");
AddErrCode(  832 , "BioAPI_BSPUnload 의 Address를 읽어오지 못했습니다.");
AddErrCode(  833 , "BioAPI_BSPAttach 의 Address를 읽어오지 못했습니다.");
AddErrCode(  834 , "BioAPI_BSPDetach 의 Address를 읽어오지 못했습니다.");
AddErrCode(  835 , "BioAPI_Enroll 의 Address를 읽어오지 못했습니다.");
AddErrCode(  836 , "BioAPI_Verify 의 Address를 읽어오지 못했습니다.");
AddErrCode(  837 , "BioAPI_CreateTemplate 의 Address를 읽어오지 못했습니다.2");
AddErrCode(  838 , "BioAPI_GetBIRFromHandle 의 Address를 읽어오지 못했습니다.");
AddErrCode(  839 , "BioAPI_FreeBIRHandle 의 Address를 읽어오지 못했습니다.");
AddErrCode(  840 , "BioAPI_Free 의 Address를 읽어오지 못했습니다.");
AddErrCode(  841 , "초기화에 실패했습니다");
AddErrCode(  842 , "FrameWork 설치에 실패했습니다. ");
AddErrCode(  843 , "BioAPI_EnumBSPs에 실패했습니다");
AddErrCode(  844 , "BioApi라이브러리가 설치 되지 않았습니다");
AddErrCode(  845 , "BioAPI_BSPLoad 실패했습니다");
AddErrCode(  846 , "BioAPI_BSPAttach 실패했습니다");
AddErrCode(  847 , "초기화 되지 않았습니다");
AddErrCode(  848 , "지문등록에 실패했습니다");
AddErrCode(  849 , "지문데이터 변환에 실패했습니다");
AddErrCode(  850 , "스캔한 지문데이터에 이상이 있습니다");
AddErrCode(  851 , "스캔한 지문데이터에 이상이 있습니다");
AddErrCode(  852 , "초기화 되지 않았습니다. ");
AddErrCode(  853 , "토큰에 지문데이터가 없습니다.");
AddErrCode(  854 , "초기화 되지 않았습니다");
AddErrCode(  856 , "토큰에 지문이 없습니다.");
AddErrCode(  857 , "지문 검증에 실패했습니다");
AddErrCode(  858 , "초기화 되지 않았습니다");
AddErrCode(  859 , "토큰에 적힌 내용에 이상이 있습니다. Enroll을 다시해 주세요");
AddErrCode(  860 , "토큰에 지문데이터가 없습니다.");
AddErrCode(  861 , "지문 검증에 실패했습니다");
AddErrCode(  862 , "payload 변경에 실패했습니다");
AddErrCode(  863 , "지문 데이터 변환에 실패했습니다");
AddErrCode(  864 , "NTGBioBSP20.dll 이 설치되지 않았습니다.");
AddErrCode(  865 , "BioSPIRI_BSPGetSchema 의 Address를 읽어오지 못했습니다.");
AddErrCode(  866 , "BioSPI_Free 의 Address를 읽어오지 못했습니다.");
AddErrCode(  867 , "BioAPI_Util_InstallBSP 의 Address를 읽어오지 못했습니다.");
AddErrCode(  868 , "스키마를 불러오지 못했습니다.");
AddErrCode(  869 , "스키마 등록에 실패했습니다.");
AddErrCode(  870 , "DSS_FP_Initialize를 호출하지 않았습니다.");
AddErrCode(  871 , "초기화에 실패했습니다");
AddErrCode(  872 , "초기화에 실패했습니다");
AddErrCode(  873 , "초기화에 실패했습니다");
AddErrCode(  874 , "초기화에 실패했습니다");
AddErrCode(  875 , "초기화에 실패했습니다");
AddErrCode(  876 , "지문인증 장치 오픈에 실패했습니다. ");
AddErrCode(  877 , "지문인증 장치 오픈에 실패했습니다. ");
AddErrCode(  878 , "초기화가 이루어 지지 않은 상태에서  DeviceClose함수를 호출했습니다.");
AddErrCode(  879 , "장치 닫기에 실패했습니다. ");
AddErrCode(  880 , "초기화 되지 않았습니다. ");
AddErrCode(  881 , "지문등록을 실패했습니다. ");
AddErrCode(  882 , "지문데이터 변환에 실패했습니다");
AddErrCode(  883 , "스캔한 지문데이터에 이상이 있습니다. ");
AddErrCode(  884 , "스캔한 지문데이터에 이상이 있습니다. ");
AddErrCode(  885 , "토큰에 적힌 내용에 이상이 있습니다. Enroll을 다시해 주세요");
AddErrCode(  886 , "초기화가 되지 않았습니다. ");
AddErrCode(  887 , "토큰에 지문이 없거나 이상이 있습니다. 다시 Enroll을 해주십시요. ");
AddErrCode(  888 , "토큰에 지문데이터가 없습니다.");
AddErrCode(  889 , "지문 검증에 실패했습니다. ");
AddErrCode(  890 , "디바이스 오픈에 실패했습니다. ");
AddErrCode(  891 , "초기화가 되지 않았습니다. ");
AddErrCode(  892 , "토큰에 적힌 내용에 이상이 있습니다. Enroll을 다시해 주세요. ");
AddErrCode(  893 , "토큰에 지문데이터가 없습니다. ");
AddErrCode(  894 , "지문 검증에 실패했습니다. ");
AddErrCode(  895 , "payload 변경에 실패했습니다. ");
AddErrCode(  896 , "지문 데이터 변환에 실패했습니다. ");
AddErrCode(  897 , "초기화가 되지 않았습니다. ");
AddErrCode(  898 , "토큰에 지문데이터가 없습니다. ");

