
/* ------------------------- usrinc/tip.h --------------------- */
/*								*/
/*              Copyright (c) 2000 Tmax Soft Co., Ltd		*/
/*                   All Rights Reserved  			*/
/*								*/
/* ------------------------------------------------------------ */

#ifndef _TMAX_TIP_H
#define _TMAX_TIP_H

#ifndef _WIN32
#define __cdecl
#endif

/*
 * TIP error messages: TIP_ERROR field
 */

#define	TIPNOERR	0
#define TIPEBADFLD	1	/* bad field key */
#define	TIPEIMPL	2	/* unimplemented request */
#define	TIPEAUTH	3	/* authrization check fail */
#define	TIPEOS		4	/* OS errors such as malloc fail */


/*
 * TIP uses predefined FDL numbers.
 * TMAX FDL header file. automatically generated by fdlc
 */

#define TIP_OPERATION 	 ((FLDKEY)485762049) /* number: 16000001 type: string */ 
#define TIP_SEGMENT 	 ((FLDKEY)485762050) /* number: 16000002 type: string */ 
#define TIP_SECTION 	 ((FLDKEY)485762051) /* number: 16000003 type: string */ 
#define TIP_NODE 	 ((FLDKEY)485762052) /* number: 16000004 type: string */ 
#define TIP_OCCURS 	 ((FLDKEY)217326597) /* number: 16000005 type: int */ 
#define TIP_FLAGS 	 ((FLDKEY)217326598) /* number: 16000006 type: int */ 
#define TIP_CURSOR 	 ((FLDKEY)485762055) /* number: 16000007 type: string */ 
#define TIP_SESTM 	 ((FLDKEY)217326600) /* number: 16000008 type: int */ 
#define TIP_ERROR 	 ((FLDKEY)217326601) /* number: 16000009 type: int */ 
#define TIP_STATE 	 ((FLDKEY)217326602) /* number: 16000010 type: int */ 
#define TIP_MORE 	 ((FLDKEY)217326603) /* number: 16000011 type: int */ 
#define TIP_BADFIELD 	 ((FLDKEY)217326604) /* number: 16000012 type: int */ 
#define TIP_NAME 	 ((FLDKEY)485762148) /* number: 16000100 type: string */ 
#define TIP_SHMKEY 	 ((FLDKEY)217326693) /* number: 16000101 type: int */ 
#define TIP_MINCLH 	 ((FLDKEY)217326694) /* number: 16000102 type: int */ 
#define TIP_MAXCLH 	 ((FLDKEY)217326695) /* number: 16000103 type: int */ 
#define TIP_MAXUSER 	 ((FLDKEY)217326696) /* number: 16000104 type: int */ 
#define TIP_TPORTNO 	 ((FLDKEY)217326697) /* number: 16000105 type: int */ 
#define TIP_RACPORT 	 ((FLDKEY)217326698) /* number: 16000106 type: int */ 
#define TIP_MAXSACALL 	 ((FLDKEY)217326699) /* number: 16000107 type: int */ 
#define TIP_MAXCACALL 	 ((FLDKEY)217326700) /* number: 16000108 type: int */ 
#define TIP_MAXCONV_NODE 	 ((FLDKEY)217326701) /* number: 16000109 type: int */ 
#define TIP_MAXCONV_SERVER 	 ((FLDKEY)217326702) /* number: 16000110 type: int */ 
#define TIP_CMTRET 	 ((FLDKEY)217326703) /* number: 16000111 type: int */ 
#define TIP_BLOCKTIME 	 ((FLDKEY)217326704) /* number: 16000112 type: int */ 
#define TIP_TXTIME 	 ((FLDKEY)217326705) /* number: 16000113 type: int */ 
#define TIP_IDLETIME 	 ((FLDKEY)217326706) /* number: 16000114 type: int */ 
#define TIP_CLICHKINT 	 ((FLDKEY)217326707) /* number: 16000115 type: int */ 
#define TIP_NLIVEINQ 	 ((FLDKEY)217326708) /* number: 16000116 type: int */ 
#define TIP_SECURITY 	 ((FLDKEY)485762165) /* number: 16000117 type: string */ 
#define TIP_OWNER 	 ((FLDKEY)485762166) /* number: 16000118 type: string */ 
#define TIP_CPC 	 ((FLDKEY)217326711) /* number: 16000119 type: int */ 
#define TIP_NCLHCHKTIME 	 ((FLDKEY)217326714) /* number: 16000122 type: int */ 
#define TIP_DOMAINID 	 ((FLDKEY)217326715) /* number: 16000123 type: int */ 
#define TIP_IPCPERM 	 ((FLDKEY)217326716) /* number: 16000124 type: int */ 
#define TIP_MAXNODE 	 ((FLDKEY)217326717) /* number: 16000125 type: int */ 
#define TIP_MAXSVG 	 ((FLDKEY)217326718) /* number: 16000126 type: int */ 
#define TIP_MAXSVR 	 ((FLDKEY)217326719) /* number: 16000127 type: int */ 
#define TIP_MAXSVC 	 ((FLDKEY)217326720) /* number: 16000128 type: int */ 
#define TIP_MAXSPR 	 ((FLDKEY)217326721) /* number: 16000129 type: int */ 
#define TIP_MAXTMS 	 ((FLDKEY)217326722) /* number: 16000130 type: int */ 
#define TIP_MAXCPC 	 ((FLDKEY)217326723) /* number: 16000131 type: int */ 
#define TIP_MAXROUT 	 ((FLDKEY)217326724) /* number: 16000132 type: int */ 
#define TIP_MAXROUTSVG 	 ((FLDKEY)217326725) /* number: 16000133 type: int */ 
#define TIP_MAXRQ 	 ((FLDKEY)217326726) /* number: 16000134 type: int */ 
#define TIP_MAXGW 	 ((FLDKEY)217326727) /* number: 16000135 type: int */ 
#define TIP_MAXCOUSIN 	 ((FLDKEY)217326728) /* number: 16000136 type: int */ 
#define TIP_MAXCOUSINSVG 	 ((FLDKEY)217326729) /* number: 16000137 type: int */ 
#define TIP_MAXBACKUP 	 ((FLDKEY)217326730) /* number: 16000138 type: int */ 
#define TIP_MAXBACKUPSVG 	 ((FLDKEY)217326731) /* number: 16000139 type: int */ 
#define TIP_MAXTOTALSVG 	 ((FLDKEY)217326732) /* number: 16000140 type: int */ 
#define TIP_MAXPROD 	 ((FLDKEY)217326733) /* number: 16000141 type: int */ 
#define TIP_MAXFUNC 	 ((FLDKEY)217326734) /* number: 16000142 type: int */ 
#define TIP_NO 	 ((FLDKEY)217326735) /* number: 16000143 type: int */ 
#define TIP_DOMAINNAME 	 ((FLDKEY)485762249) /* number: 16000201 type: string */ 
#define TIP_CLHQTIMEOUT 	 ((FLDKEY)217326797) /* number: 16000205 type: int */ 
#define TIP_TMAXDIR 	 ((FLDKEY)485762264) /* number: 16000216 type: string */ 
#define TIP_APPDIR 	 ((FLDKEY)485762265) /* number: 16000217 type: string */ 
#define TIP_PATHDIR 	 ((FLDKEY)485762266) /* number: 16000218 type: string */ 
#define TIP_TLOGDIR 	 ((FLDKEY)485762267) /* number: 16000219 type: string */ 
#define TIP_SLOGDIR 	 ((FLDKEY)485762268) /* number: 16000220 type: string */ 
#define TIP_ULOGDIR 	 ((FLDKEY)485762269) /* number: 16000221 type: string */ 
#define TIP_ENVFILE 	 ((FLDKEY)485762270) /* number: 16000222 type: string */ 
#define TIP_IP 	 ((FLDKEY)485762273) /* number: 16000225 type: string */ 
#define TIP_TMMOPT 	 ((FLDKEY)485762275) /* number: 16000227 type: string */ 
#define TIP_CLHOPT 	 ((FLDKEY)485762276) /* number: 16000228 type: string */ 
#define TIP_NODENAME 	 ((FLDKEY)485762349) /* number: 16000301 type: string */ 
#define TIP_SVGTYPE 	 ((FLDKEY)485762350) /* number: 16000302 type: string */ 
#define TIP_COUSIN 	 ((FLDKEY)485762352) /* number: 16000304 type: string */ 
#define TIP_BACKUP 	 ((FLDKEY)485762353) /* number: 16000305 type: string */ 
#define TIP_LOAD 	 ((FLDKEY)217326898) /* number: 16000306 type: int */ 
#define TIP_DBNAME 	 ((FLDKEY)485762357) /* number: 16000309 type: string */ 
#define TIP_OPENINFO 	 ((FLDKEY)485762358) /* number: 16000310 type: string */ 
#define TIP_CLOSEINFO 	 ((FLDKEY)485762359) /* number: 16000311 type: string */ 
#define TIP_MINTMS 	 ((FLDKEY)217326904) /* number: 16000312 type: int */ 
#define TIP_TMSNAME 	 ((FLDKEY)485762362) /* number: 16000314 type: string */ 
#define TIP_SVGNAME 	 ((FLDKEY)485762399) /* number: 16000351 type: string */ 
#define TIP_CLOPT 	 ((FLDKEY)485762401) /* number: 16000353 type: string */ 
#define TIP_SEQ 	 ((FLDKEY)217326946) /* number: 16000354 type: int */ 
#define TIP_MIN 	 ((FLDKEY)217326947) /* number: 16000355 type: int */ 
#define TIP_MAX 	 ((FLDKEY)217326948) /* number: 16000356 type: int */ 
#define TIP_CONV 	 ((FLDKEY)217326950) /* number: 16000358 type: int */ 
#define TIP_MAXQCOUNT 	 ((FLDKEY)217326951) /* number: 16000359 type: int */ 
#define TIP_ASQCOUNT 	 ((FLDKEY)217326952) /* number: 16000360 type: int */ 
#define TIP_MAXRSTART 	 ((FLDKEY)217326953) /* number: 16000361 type: int */ 
#define TIP_GPERIOD 	 ((FLDKEY)217326954) /* number: 16000362 type: int */ 
#define TIP_RESTART 	 ((FLDKEY)217326955) /* number: 16000363 type: int */ 
#define TIP_SVRTYPE 	 ((FLDKEY)485762412) /* number: 16000364 type: string */ 
#define TIP_TARGET 	 ((FLDKEY)485762416) /* number: 16000368 type: string */ 
#define TIP_SVRNAME 	 ((FLDKEY)485762449) /* number: 16000401 type: string */ 
#define TIP_PRI 	 ((FLDKEY)217326994) /* number: 16000402 type: int */ 
#define TIP_SVCTIME 	 ((FLDKEY)217326995) /* number: 16000403 type: int */ 
#define TIP_ROUTING 	 ((FLDKEY)485762452) /* number: 16000404 type: string */ 
#define TIP_SUBTYPE 	 ((FLDKEY)485762474) /* number: 16000426 type: string */ 
#define TIP_FIELD 	 ((FLDKEY)485762475) /* number: 16000427 type: string */ 
#define TIP_RANGES 	 ((FLDKEY)485762476) /* number: 16000428 type: string */ 
#define TIP_PRESVC 	 ((FLDKEY)485762500) /* number: 16000452 type: string */ 
#define TIP_QSIZE 	 ((FLDKEY)217327045) /* number: 16000453 type: int */ 
#define TIP_FILEPATH 	 ((FLDKEY)485762502) /* number: 16000454 type: string */ 
#define TIP_BOOT 	 ((FLDKEY)485762503) /* number: 16000455 type: string */ 
#define TIP_FSYNC 	 ((FLDKEY)217327048) /* number: 16000456 type: int */ 
#define TIP_BUFFERING 	 ((FLDKEY)217327049) /* number: 16000457 type: int */ 
#define TIP_GWTYPE 	 ((FLDKEY)485762549) /* number: 16000501 type: string */ 
#define TIP_PORTNO 	 ((FLDKEY)217327094) /* number: 16000502 type: int */ 
#define TIP_RGWADDR 	 ((FLDKEY)485762552) /* number: 16000504 type: string */ 
#define TIP_RGWPORTNO 	 ((FLDKEY)217327097) /* number: 16000505 type: int */ 
#define TIP_KEY 	 ((FLDKEY)485762556) /* number: 16000508 type: string */ 
#define TIP_BACKUP_RGWADDR 	 ((FLDKEY)485762557) /* number: 16000509 type: string */ 
#define TIP_BACKUP_RGWPORTNO 	 ((FLDKEY)217327102) /* number: 16000510 type: int */ 
#define TIP_TIMEOUT 	 ((FLDKEY)217327103) /* number: 16000511 type: int */ 
#define TIP_FQSTART 	 ((FLDKEY)217327144) /* number: 16000552 type: int */ 
#define TIP_FQEND 	 ((FLDKEY)217327145) /* number: 16000553 type: int */ 
#define TIP_ENTRY 	 ((FLDKEY)485762602) /* number: 16000554 type: string */ 
#define TIP_STATUS 	 ((FLDKEY)485762649) /* number: 16000601 type: string */ 
#define TIP_STIME 	 ((FLDKEY)217327194) /* number: 16000602 type: int */ 
#define TIP_TTIME 	 ((FLDKEY)217327195) /* number: 16000603 type: int */ 
#define TIP_SVC_STIME 	 ((FLDKEY)217327196) /* number: 16000604 type: int */ 
#define TIP_COUNT 	 ((FLDKEY)217327197) /* number: 16000605 type: int */ 
#define TIP_NUM_FREE 	 ((FLDKEY)217327199) /* number: 16000607 type: int */ 
#define TIP_NUM_REPLY 	 ((FLDKEY)217327200) /* number: 16000608 type: int */ 
#define TIP_NUM_FAIL 	 ((FLDKEY)217327201) /* number: 16000609 type: int */ 
#define TIP_NUM_REQ 	 ((FLDKEY)217327202) /* number: 16000610 type: int */ 
#define TIP_ENQ_REQS 	 ((FLDKEY)217327203) /* number: 16000611 type: int */ 
#define TIP_DEQ_REQS 	 ((FLDKEY)217327204) /* number: 16000612 type: int */ 
#define TIP_ENQ_REPLYS 	 ((FLDKEY)217327205) /* number: 16000613 type: int */ 
#define TIP_DEQ_REPLYS 	 ((FLDKEY)217327206) /* number: 16000614 type: int */ 
#define TIP_CLHNO 	 ((FLDKEY)217327207) /* number: 16000615 type: int */ 
#define TIP_SVR_NAME 	 ((FLDKEY)485762664) /* number: 16000616 type: string */ 
#define TIP_SVC_NAME 	 ((FLDKEY)485762665) /* number: 16000617 type: string */ 
#define TIP_AVERAGE 	 ((FLDKEY)351544938) /* number: 16000618 type: float */ 
#define TIP_QCOUNT 	 ((FLDKEY)217327211) /* number: 16000619 type: int */ 
#define TIP_CQCOUNT 	 ((FLDKEY)217327212) /* number: 16000620 type: int */ 
#define TIP_QAVERAGE 	 ((FLDKEY)351544941) /* number: 16000621 type: float */ 


#endif       /* end of _TMAX_TIP_H  */
